### ISSUE TITLE
Build failure: Unable to checkout 'chibios @ e7a5b54' in submodule path 'firmware/chibios'

### ISSUE THREAD

**Issue by geosmall** [PX4/px4esc#15]
Ubuntu 14.04.3 LTS
Toolchain per http://dev.px4.io/starting-installing-linux.html (NuttX based hardware)
Build per: http://dev.px4.io/uavcan-node-firmware.html (PX4 ESC Codebase (Pixhawk ESC 1.4))

Pixhawk firmwares and Pixhawk ESC 1.6 compile successfully on same machine.

Summary::

Build fails with [Unable to checkout 'e7a5b54dee336bb632b9b767e2001103c65a33ee' in submodule path 'firmware/chibios'] error, specifically:
fatal: reference is not a tree: e7a5b54dee336bb632b9b767e2001103c65a33ee

https://github.com/Zubax/ChibiOS/tree/e7a5b54dee336bb632b9b767e2001103c65a33ee throws a 404 error.

Terminal:

geo@geo-Latitude-E6530:~/src$ git clone https://github.com/PX4/px4esc.git
Cloning into 'px4esc'...
remote: Counting objects: 2964, done.
remote: Total 2964 (delta 0), reused 0 (delta 0), pack-reused 2964
Receiving objects: 100% (2964/2964), 993.18 KiB | 1.14 MiB/s, done.
Resolving deltas: 100% (2095/2095), done.
Checking connectivity... done.
geo@geo-Latitude-E6530:~/src$ cd px4esc
geo@geo-Latitude-E6530:~/src/px4esc$ git submodule update --init --recursive
Submodule 'firmware/chibios' (https://github.com/Zubax/ChibiOS) registered for path 'firmware/chibios'
Submodule 'firmware/uavcan' (https://github.com/UAVCAN/uavcan) registered for path 'firmware/uavcan'
Cloning into 'firmware/chibios'...
remote: Counting objects: 101032, done.
remote: Total 101032 (delta 0), reused 0 (delta 0), pack-reused 101032
Receiving objects: 100% (101032/101032), 37.13 MiB | 1.18 MiB/s, done.
Resolving deltas: 100% (80130/80130), done.
Checking connectivity... done.
fatal: reference is not a tree: e7a5b54dee336bb632b9b767e2001103c65a33ee
Cloning into 'firmware/uavcan'...
remote: Counting objects: 16540, done.
remote: Total 16540 (delta 0), reused 0 (delta 0), pack-reused 16540
Receiving objects: 100% (16540/16540), 2.66 MiB | 1.30 MiB/s, done.
Resolving deltas: 100% (11188/11188), done.
Checking connectivity... done.
Submodule path 'firmware/uavcan': checked out '6dd432c9742c22e1dd1638c7f91cf937e4bdb2f1'
Unable to checkout 'e7a5b54dee336bb632b9b767e2001103c65a33ee' in submodule path 'firmware/chibios'
geo@geo-Latitude-E6530:~/src/px4esc$ cd firmware
geo@geo-Latitude-E6530:~/src/px4esc/firmware$ make RELEASE=1
Running from the source directory
Makefile:87: chibios/os/hal/platforms/STM32F4xx/platform.mk: No such file or directory
Makefile:88: chibios/os/hal/hal.mk: No such file or directory
Makefile:89: chibios/os/ports/GCC/ARMCMx/STM32F2xx/port.mk: No such file or directory
Makefile:90: chibios/os/kernel/kernel.mk: No such file or directory
Makefile:91: chibios/os/various/cpp_wrappers/kernel.mk: No such file or directory
Makefile:168: chibios/os/ports/GCC/ARMCMx/rules.mk: No such file or directory
make: *** No rule to make target `chibios/os/ports/GCC/ARMCMx/rules.mk'.  Stop.
geo@geo-Latitude-E6530:~/src/px4esc/firmware$

**Comment by pavel-kirienko** [comment]
Fixed. Thanks for reporting.

**Comment by geosmall** [comment]
Sure no problem.  PX4ESC in PX4 Git appears fixed but documentation still points to  https://github.com/thiemar/px4esc which appears to still be broken.

**Comment by pavel-kirienko** [comment]
Should be fixed with https://github.com/PX4/Devguide/pull/55.

**Comment by pavel-kirienko** [comment]
Note that per https://github.com/PX4/px4esc/issues/12, the branch `pixhawk_esc_v1.4` is gone - now you should use master instead.
