### ISSUE TITLE
CAN Bootloader

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/px4esc#2]
As soon as we move from ESC developers to autopilot developers for testing, updating the ESC firmware will become painful (in particular if they are mounted in vehicles). We should bundle the ESC firmware in the autopilot flash (we're doing this already for PX4IO) and bootload all ESCs via CAN if the CRC of their FW (which they provide on request) differs from the autopilot's FW version. This also ensures compatibility.

**Comment by LorenzMeier** [comment]
@pavel-kirienko Is there a reason we couldn't flash a CAN boot loader into the lower flash memory region? The application level binary is 170K, I presume a build without CLI just for boot loading would be much smaller? That seems a lot easier than going with the hardware requirements of the in-built boot loader?

**Comment by pavel-kirienko** [comment]
We discussed it with Philip:

> If you don't have an external storage, you'll need to squeeze a part of UAVCAN stack inside the bootloader. Cons:
- it takes space (I think the bootloader will be around 40k)
- you can't upgrade the bootloader's UAVCAN stack implementation
- you'll need to pass a couple of parameters to the bootloader (e.g. Node ID, CAN bus speed, etcc)
- if bootloading fails and you want to re-run it, how do you change UAVCAN parameters again?

Yes, we can deal without an external flash, if the shortcomings above can be tolerated. Considering that a suitable flash chip would be quite cheap, I think we should use the right approach.

> That seems a lot easier than going with the hardware requirements of the in-built boot loader?

Quite the opposite - from the firmware and usability standpoint, the solution with temporary storage would be easier to implement and use.

**Comment by LorenzMeier** [comment]
I see your point as you can work with a single image and swap it out. I do see two main drawbacks:
  * The need for external flash with the associated cost and board space. Not a big deal for high-end, low-volume designs, but an obstacle for broad UAVCAN adoption
  * The double buffer scheme means a bad application binary can completely brick the ESC, as it will over-write itself on the next update

The bootloader would be still upgradable via the normal firmware (e.g. FMU can upgrade its own bootloader on command).

**Comment by LorenzMeier** [comment]
@pavel-kirienko Do you have feedback on this? In particular the 2nd item is of great concern to me, since a bricked ESC means a recall of the affected boards and the associated huge costs. Its not necessarily a position we want to put ourselves in.

**Comment by pavel-kirienko** [comment]
Re the first point - I agree that there's some extra cost involved, but I don't see how it can prevent UAVCAN adoption, as PX4ESC is just one particular use case and it doesn't define anything globally, standard-wise. We already agreed that both solutions can be implemented, the question is what is more suitable in our case.

Re the second item - in the approach I proposed, the bootloader is not supposed to be upgraded over UAVCAN, which means that whatever firmware is loaded, the bootloader stays intact. If you meant that a bad application can be loaded that, being broken, can't communicate over UAVCAN and hence can't be replaced again, then yes, it's an issue, but it's inherent to both approaches we're discussing here. And the chances of this happening can be minimized by means of careful checking of firmware binaries for compatibility with the hardware. If a bad firmware somehow still manages to be flashed, it will have to be replaced in some other way, e.g. using bootloader via UART or USB if available (no product recall involved).

In the scheme without an external memory there's an issue that I mentioned above - invoking the UAVCAN-capable bootloader requires it to have some configurable parameters (or share some configuration parameters with the main firmware), which further complicates the bootloader (increasing likelihood that it will require an update), and which can pose a significant issue if the bootloader gets invoked with wrong parameters. The last one calls for a way to alter the parameters of the bootloader while it is running, which almost turns it into a full-fledged UAVCAN node on its own.

Again, I'm not saying that an external flash is required, I'm just pointing out that it is hard to deal without one.
